#!/usr/bin/with-contenv bash

import_cron () {
    if [ ! -d /config ]; then
        echo "没有映射config配置目录给本容器，在容器内创建该文件夹。"
        mkdir -p /config
    fi
    if [ -f /config/crontab.list ]; then
        crontab /config/crontab.list
    fi
}

import_cron 2>&1 | perl -pe "s|^(.+)|[cont-init.d] $(basename $0): \1|g"
