#!/usr/bin/with-contenv bash

set_crontab() {
    if [[ -z ${CRON_HEALTH_CHECK} ]]; then
        CRON_HEALTH_CHECK="12 * * * *"
    fi

    if [[ -z ${CRON_AUTO_CATEGORY} ]]; then
        CRON_AUTO_CATEGORY="32 */2 * * *"
    fi

    if [[ -z ${CRON_TRACKER_ERROR} ]]; then
        CRON_TRACKER_ERROR="52 */4 * * *"
    fi

    echo "Set crontab to system..."
    echo -e "${CRON_HEALTH_CHECK} health-check\n${CRON_AUTO_CATEGORY} auto-cat -a\n${CRON_TRACKER_ERROR} tracker-error" | crontab -
}

set_crontab 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"